name: 🤖 Build and Deploy web - Production

on:
  workflow_dispatch:
    inputs:
      skip_e2e:
        description: Skip e2e tests
        default: 'false'
        required: false
        type: choice
        options:
          - 'false'
          - 'true'

jobs:
  e2e:
    name: E2E tests
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.skip_e2e == 'false' }}
    steps:
      # fail the jo
      - name: fail exit
        run: exit 1

  build:
    needs: e2e
    runs-on: ubuntu-latest
    if: always() && (needs.e2e.result == 'skipped' || needs.e2e.result == 'success')
    steps:
      - name: echo success
        run: echo "success"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: always() && needs.build.result == 'success'
    steps:
      - name: echo success
        run: echo "success"

  githubTag:
    needs: deploy
    if: always() && needs.deploy.result == 'success'
    #runs-on: [ self-hosted, linux ]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Create web production tag
    environment:
      name: production
    steps:
      - name: echo success
        run: echo "success"

  slackNotifyE2Efail:
    needs: e2e
    if: always() && needs.e2e.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: echo success
        run: echo "success"
